apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: system
  labels:
    component: webhook
    app.kubernetes.io/name: webhook
    app.kubernetes.io/instance: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: webhook
    app.kubernetes.io/part-of: webhook
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: webhook
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: webhook
      labels:
        control-plane: webhook
        component: webhook
    spec:
      containers:
      - command:
        - /nodemarker
        args:
        - "--loglevel=debug"
        - "--namespace=$(NAMESPACE)"
        - "--disable-cert-rotation=true"
        - "--webhookmode=webhookonly"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: controller:main
        imagePullPolicy: IfNotPresent
        name: webhook
        ports:
          - containerPort: 9443
            name: webhook-server
            protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - name: cert
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true
      serviceAccountName: controller
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: openpe-webhook-server-cert
