apiVersion: v1
kind: Namespace
metadata:
  name: openperouter-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: openperouter-operator
  namespace: openperouter-system
spec:
  displayName: OpenPERouter Operator
  image: quay.io/openperouter/openperouter-operator-bundle-index:main
  publisher: github.com/openperouter/openperouter-operator
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openperouter-operator
  namespace: openperouter-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openperouter-operator-sub
  namespace: openperouter-system
spec:
  name: openperouter-operator
  channel: alpha
  source: openperouter-operator
  sourceNamespace: openperouter-system
