apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: workload
spec:
  selector:
    matchLabels:
      app: workload
  template:
    metadata:
      labels:
        app: workload
    spec:
      containers:
      - name: workload
        imagePullPolicy: IfNotPresent
        image: fedora:net
        ports:
        - name: http
          containerPort: 80
        command: ["sleep",  "inf"]
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists

