apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controller
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: controller
          volumeMounts:
          - mountPath: /crio.sock
            name: varrun
            subPath: crio.sock
          args:
          - "--nodename=$(NODE_NAME)"
          - "--loglevel=debug"
          - "--namespace=$(NAMESPACE)"
          - "--frrconfig=/etc/frr/frr.conf"
          - "--crisocket=/crio.sock"
      volumes:
      - name: varrun
        hostPath:
          path: /var/run/crio
