---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - openpe-validating-webhook-configuration
  resources:
  - validatingwebhookconfigurations
  verbs:
  - update
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - l2vnis
  - l3passthroughs
  - l3vnis
  - underlays
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - l2vnis/finalizers
  - l3passthroughs/finalizers
  - l3vnis/finalizers
  - underlays/finalizers
  verbs:
  - update
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - l2vnis/status
  - l3passthroughs/status
  - l3vnis/status
  - underlays/status
  verbs:
  - get
  - patch
  - update
