apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agnhost-daemonset
spec:
  selector:
    matchLabels:
      app: agnhost
  template:
    metadata:
      labels:
        app: agnhost
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: agnhost
        image: k8s.gcr.io/e2e-test-images/agnhost:2.45
        command: ["/agnhost", "netexec", "--http-port=8090"]
        ports:
        - containerPort: 8090
          name: http