// SPDX-License-Identifier:Apache-2.0

package infra

import (
	"encoding/json"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
)

// IPFamily represents the IP address family.
type IPFamily int

const (
	IPv4 IPFamily = iota
	IPv6
)

// TopologyState mirrors the JSON schema produced by clab-config apply.
type TopologyState struct {
	InputHash         string                `json:"inputHash"`
	TopologyName      string                `json:"topologyName"`
	Nodes             map[string]*NodeState `json:"nodes"`
	Links             []LinkState           `json:"links"`
	BroadcastNetworks []BroadcastNetwork    `json:"broadcastNetworks"`
}

type NodeState struct {
	Name           string                     `json:"name"`
	MatchedPattern string                     `json:"matchedPattern"`
	Role           string                     `json:"role"`
	RouterID       string                     `json:"routerID"`
	VTEPIP         string                     `json:"vtepIP,omitempty"`
	Interfaces     map[string]*InterfaceState `json:"interfaces"`
	VRFs           map[string]*VRFState       `json:"vrfs,omitempty"`
	BGP            *BGPState                  `json:"bgp"`
}

type InterfaceState struct {
	Name          string `json:"name"`
	PeerNode      string `json:"peerNode"`
	PeerInterface string `json:"peerInterface"`
	IPv4          string `json:"ipv4"`
	IPv6          string `json:"ipv6"`
	LinkType      string `json:"linkType"`
}

type VRFState struct {
	Name                  string   `json:"name"`
	VNI                   int      `json:"vni"`
	Interfaces            []string `json:"interfaces"`
	RedistributeConnected bool     `json:"redistributeConnected"`
	MACAddress            string   `json:"macAddress"`
	BridgeID              int      `json:"bridgeID"`
}

type LinkState struct {
	NodeA      string `json:"nodeA"`
	InterfaceA string `json:"interfaceA"`
	NodeB      string `json:"nodeB"`
	InterfaceB string `json:"interfaceB"`
	IPv4Subnet string `json:"ipv4Subnet"`
	IPv6Subnet string `json:"ipv6Subnet"`
	Type       string `json:"type"`
}

type BroadcastNetwork struct {
	SwitchName string            `json:"switchName"`
	IPv4Subnet string            `json:"ipv4Subnet"`
	IPv6Subnet string            `json:"ipv6Subnet"`
	Members    []BroadcastMember `json:"members"`
}

type BroadcastMember struct {
	NodeName      string `json:"nodeName"`
	InterfaceName string `json:"interfaceName"`
	IPv4          string `json:"ipv4"`
	IPv6          string `json:"ipv6"`
}

type BGPState struct {
	ASN   uint32         `json:"asn"`
	Peers []BGPPeerState `json:"peers"`
}

type BGPPeerState struct {
	NodeName    string `json:"nodeName"`
	ASN         uint32 `json:"asn"`
	IPv4Address string `json:"ipv4Address"`
	IPv6Address string `json:"ipv6Address"`
	EVPNEnabled bool   `json:"evpnEnabled"`
	BFDEnabled  bool   `json:"bfdEnabled"`
}

var (
	topoOnce  sync.Once
	topoState *TopologyState
)

// Topology returns the singleton TopologyState, loading it from the
// topology-state.json file generated by clab-config apply.
func Topology() *TopologyState {
	topoOnce.Do(func() {
		_, currentFile, _, _ := runtime.Caller(0)
		// Navigate from e2etests/pkg/infra/ up to repo root, then to clab/singlecluster/
		repoRoot := filepath.Join(filepath.Dir(currentFile), "..", "..", "..")
		statePath := filepath.Join(repoRoot, "clab", "singlecluster", "topology-state.json")

		data, err := os.ReadFile(statePath)
		if err != nil {
			panic(fmt.Sprintf("failed to load topology state from %s: %v", statePath, err))
		}

		var state TopologyState
		if err := json.Unmarshal(data, &state); err != nil {
			panic(fmt.Sprintf("failed to unmarshal topology state: %v", err))
		}

		topoState = &state
	})
	return topoState
}

// ContainerName maps a clab node name to its Docker container name.
// External containers (ext-container kind) keep their original name.
// Bridge nodes are not containers. Other nodes get the "clab-<topoName>-" prefix.
func ContainerName(nodeName string) string {
	topo := Topology()
	// ext-container nodes like pe-kind-control-plane and pe-kind-worker
	// keep their original name (no clab prefix)
	switch nodeName {
	case KindControlPlane, KindWorker:
		return nodeName
	}
	return fmt.Sprintf("clab-%s-%s", topo.TopologyName, nodeName)
}

// stripCIDR removes the prefix length from a CIDR string.
func stripCIDR(addr string) string {
	if i := strings.Index(addr, "/"); i >= 0 {
		return addr[:i]
	}
	return addr
}

// GetLinkIP returns the IP address of nodeName's interface facing peerName.
func (s *TopologyState) GetLinkIP(nodeName, peerName string, family IPFamily) (string, error) {
	node, ok := s.Nodes[nodeName]
	if !ok {
		return "", fmt.Errorf("node %q not found", nodeName)
	}
	for _, iface := range node.Interfaces {
		if iface.PeerNode == peerName {
			switch family {
			case IPv4:
				if iface.IPv4 == "" {
					return "", fmt.Errorf("no IPv4 address on %s interface facing %s", nodeName, peerName)
				}
				return iface.IPv4, nil
			case IPv6:
				if iface.IPv6 == "" {
					return "", fmt.Errorf("no IPv6 address on %s interface facing %s", nodeName, peerName)
				}
				return iface.IPv6, nil
			}
		}
	}
	return "", fmt.Errorf("no interface on %s facing peer %s", nodeName, peerName)
}

// GetPeerIP returns the IP address of the peer end of a point-to-point link.
func (s *TopologyState) GetPeerIP(nodeName, peerName string, family IPFamily) (string, error) {
	// If peer is in Nodes, look up its interface directly
	if peer, ok := s.Nodes[peerName]; ok {
		for _, iface := range peer.Interfaces {
			if iface.PeerNode == nodeName {
				switch family {
				case IPv4:
					if iface.IPv4 == "" {
						return "", fmt.Errorf("no IPv4 address on %s interface facing %s", peerName, nodeName)
					}
					return iface.IPv4, nil
				case IPv6:
					if iface.IPv6 == "" {
						return "", fmt.Errorf("no IPv6 address on %s interface facing %s", peerName, nodeName)
					}
					return iface.IPv6, nil
				}
			}
		}
	}

	// Peer is not in Nodes (e.g., a host node). Compute from the node's own IP.
	nodeObj, ok := s.Nodes[nodeName]
	if !ok {
		return "", fmt.Errorf("node %q not found", nodeName)
	}
	for _, iface := range nodeObj.Interfaces {
		if iface.PeerNode == peerName {
			switch family {
			case IPv4:
				if iface.IPv4 == "" {
					return "", fmt.Errorf("no IPv4 address on %s interface facing %s", nodeName, peerName)
				}
				return otherIP(iface.IPv4), nil
			case IPv6:
				if iface.IPv6 == "" {
					return "", fmt.Errorf("no IPv6 address on %s interface facing %s", nodeName, peerName)
				}
				return otherIP(iface.IPv6), nil
			}
		}
	}
	return "", fmt.Errorf("no link found between %s and %s", nodeName, peerName)
}

// otherIP computes the other address in a /31 or /127 subnet.
func otherIP(cidr string) string {
	ip, ipNet, err := net.ParseCIDR(cidr)
	if err != nil {
		return cidr
	}
	ipBytes := ip.To16()
	if ipBytes == nil {
		return cidr
	}
	ipBytes[len(ipBytes)-1] ^= 1
	ones, _ := ipNet.Mask.Size()
	return fmt.Sprintf("%s/%d", net.IP(ipBytes).String(), ones)
}

// GetBroadcastMemberIP returns the IP address of a member in a broadcast network.
func (s *TopologyState) GetBroadcastMemberIP(switchName, nodeName string, family IPFamily) (string, error) {
	for _, bn := range s.BroadcastNetworks {
		if bn.SwitchName == switchName {
			for _, member := range bn.Members {
				if member.NodeName == nodeName {
					switch family {
					case IPv4:
						if member.IPv4 == "" {
							return "", fmt.Errorf("no IPv4 address for %s in broadcast network %s", nodeName, switchName)
						}
						return member.IPv4, nil
					case IPv6:
						if member.IPv6 == "" {
							return "", fmt.Errorf("no IPv6 address for %s in broadcast network %s", nodeName, switchName)
						}
						return member.IPv6, nil
					}
				}
			}
			return "", fmt.Errorf("node %q not found in broadcast network %q", nodeName, switchName)
		}
	}
	return "", fmt.Errorf("broadcast network %q not found", switchName)
}
