// SPDX-License-Identifier:Apache-2.0

// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadNicIngress returns the embedded CollectionSpec for NicIngress.
func LoadNicIngress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NicIngressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NicIngress: %w", err)
	}

	return spec, err
}

// LoadNicIngressObjects loads NicIngress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NicIngressObjects
//	*NicIngressPrograms
//	*NicIngressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNicIngressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNicIngress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NicIngressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NicIngressSpecs struct {
	NicIngressProgramSpecs
	NicIngressMapSpecs
	NicIngressVariableSpecs
}

// NicIngressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NicIngressProgramSpecs struct {
	NicIngress *ebpf.ProgramSpec `ebpf:"nic_ingress"`
}

// NicIngressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NicIngressMapSpecs struct {
	ConfigMap   *ebpf.MapSpec `ebpf:"config_map"`
	NeighborMap *ebpf.MapSpec `ebpf:"neighbor_map"`
	VniMap      *ebpf.MapSpec `ebpf:"vni_map"`
}

// NicIngressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NicIngressVariableSpecs struct {
}

// NicIngressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNicIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type NicIngressObjects struct {
	NicIngressPrograms
	NicIngressMaps
	NicIngressVariables
}

func (o *NicIngressObjects) Close() error {
	return _NicIngressClose(
		&o.NicIngressPrograms,
		&o.NicIngressMaps,
	)
}

// NicIngressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNicIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type NicIngressMaps struct {
	ConfigMap   *ebpf.Map `ebpf:"config_map"`
	NeighborMap *ebpf.Map `ebpf:"neighbor_map"`
	VniMap      *ebpf.Map `ebpf:"vni_map"`
}

func (m *NicIngressMaps) Close() error {
	return _NicIngressClose(
		m.ConfigMap,
		m.NeighborMap,
		m.VniMap,
	)
}

// NicIngressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNicIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type NicIngressVariables struct {
}

// NicIngressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNicIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type NicIngressPrograms struct {
	NicIngress *ebpf.Program `ebpf:"nic_ingress"`
}

func (p *NicIngressPrograms) Close() error {
	return _NicIngressClose(
		p.NicIngress,
	)
}

func _NicIngressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nicingress_bpfeb.o
var _NicIngressBytes []byte
