// SPDX-License-Identifier:Apache-2.0

// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadUlHostIngress returns the embedded CollectionSpec for UlHostIngress.
func LoadUlHostIngress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_UlHostIngressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load UlHostIngress: %w", err)
	}

	return spec, err
}

// LoadUlHostIngressObjects loads UlHostIngress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*UlHostIngressObjects
//	*UlHostIngressPrograms
//	*UlHostIngressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadUlHostIngressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadUlHostIngress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// UlHostIngressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UlHostIngressSpecs struct {
	UlHostIngressProgramSpecs
	UlHostIngressMapSpecs
	UlHostIngressVariableSpecs
}

// UlHostIngressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UlHostIngressProgramSpecs struct {
	UlHostIngress *ebpf.ProgramSpec `ebpf:"ul_host_ingress"`
}

// UlHostIngressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UlHostIngressMapSpecs struct {
	ConfigMap *ebpf.MapSpec `ebpf:"config_map"`
}

// UlHostIngressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UlHostIngressVariableSpecs struct {
}

// UlHostIngressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadUlHostIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type UlHostIngressObjects struct {
	UlHostIngressPrograms
	UlHostIngressMaps
	UlHostIngressVariables
}

func (o *UlHostIngressObjects) Close() error {
	return _UlHostIngressClose(
		&o.UlHostIngressPrograms,
		&o.UlHostIngressMaps,
	)
}

// UlHostIngressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadUlHostIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type UlHostIngressMaps struct {
	ConfigMap *ebpf.Map `ebpf:"config_map"`
}

func (m *UlHostIngressMaps) Close() error {
	return _UlHostIngressClose(
		m.ConfigMap,
	)
}

// UlHostIngressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadUlHostIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type UlHostIngressVariables struct {
}

// UlHostIngressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadUlHostIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type UlHostIngressPrograms struct {
	UlHostIngress *ebpf.Program `ebpf:"ul_host_ingress"`
}

func (p *UlHostIngressPrograms) Close() error {
	return _UlHostIngressClose(
		p.UlHostIngress,
	)
}

func _UlHostIngressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ulhostingress_bpfel.o
var _UlHostIngressBytes []byte
