apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: peerred
  namespace: metallb-system
spec:
  myASN: 64515
  peerASN: 64514
  peerAddress: 192.169.10.0
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: peerblue
  namespace: metallb-system
spec:
  myASN: 64515
  peerASN: 64514
  peerAddress: 192.169.11.0
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: address-pool-red
  namespace: metallb-system
spec:
  addresses:
    - 172.30.0.10-172.30.0.15
  autoAssign: true
  serviceAllocation:
    namespaces:
      - red
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: address-pool-blue
  namespace: metallb-system
spec:
  addresses:
    - 172.30.0.16-172.30.0.20
  autoAssign: true
  serviceAllocation:
    namespaces:
      - blue
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-advertisement-red
  namespace: metallb-system
spec:
  ipAddressPools:
    - address-pool-red
  peers:
    - peerred
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-advertisement-blue
  namespace: metallb-system
spec:
  ipAddressPools:
    - address-pool-blue
  peers:
    - peerblue
---
apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: receive-all 
  namespace: frr-k8s-system
spec:
  bgp:
    routers:
    - asn: 64515
      neighbors:
      - address: 192.169.10.0
        asn: 64514
        toReceive:
          allowed:
            mode: all
      - address: 192.169.11.0
        asn: 64514
        toReceive:
          allowed:
            mode: all
