frr version 10.2.1_git
frr defaults traditional
hostname leafkind
log file /etc/frr/frr.log
!
debug zebra events
debug zebra kernel
debug zebra rib
debug zebra nht
debug zebra vxlan
debug zebra nexthop
debug bgp keepalives
debug bgp neighbor-events
debug bgp nht
debug bgp updates in
debug bgp updates out
debug bgp zebra
debug bfd peer
debug bfd zebra
debug bfd network
!
router bgp 64512
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 no bgp network import-check
 neighbor 192.168.1.4 remote-as 64612
 neighbor 192.168.11.3 remote-as 64514
 neighbor 192.168.11.4 remote-as 64514
 !
 address-family ipv4 unicast
  neighbor 192.168.1.4 activate
  neighbor 192.168.11.3 activate
  neighbor 192.168.11.4 activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 192.168.1.4 activate
  neighbor 192.168.11.3 activate
  neighbor 192.168.11.4 activate
  advertise-all-vni
  advertise-svi-ip
 exit-address-family
exit
!
