apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: openperouter-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Underlay is the Schema for the underlays API.
      displayName: Underlay
      kind: Underlay
      name: underlays.openpe.openperouter.github.io
      version: v1alpha1
    - description: |-
        VNI represents a VXLan VNI to receive EVPN type 5 routes
        from.
      displayName: VNI
      kind: VNI
      name: vnis.openpe.openperouter.github.io
      version: v1alpha1
    - description: OpenPERouter is the Schema for the openperouters API
      displayName: Open PERouter
      kind: OpenPERouter
      name: openperouters.openpe.openperouter.github.io
      version: v1alpha1
  description: An operator for deploying OpenPERouter on a Kubernetes cluster.
  displayName: OpenPERouter Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - openperouter-operator
  links:
  - name: OpenPERouter Operator
    url: https://github.com/openperouter/openperouter
  maintainers:
  - email: fpaoline@redhat.com
    name: Federico Paolinelli
  maturity: alpha
  provider:
    name: Community
    url: https://github.com/openperouter/openperouter
  version: 0.0.0
