name: Publish
on:
  push:
    branches:
      - "main"
      - v*


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-website:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.PUBLISH_APP_ID }}
          private_key: ${{ secrets.PUBLISH_APP_PRIVATE_KEY }}
          repositories: |
            openperouter.github.io

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Publish Website
        run: |
          make publish-website
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
