[Container]
Exec=--frrconfig /etc/perouter/frr/frr.conf --pid-path /etc/perouter/frr/frr.pid --reloader-socket /etc/perouter/frr/frr.socket --mode host --namespace openperouter-system --router-netns /hostproc/1/ns/net --cni-plugin-dirs=/opt/openperouter/cni/bin/ --cni-cache-dir=/var/lib/openperouter/cni/cache
